version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.60
    container_name: jaeger-reg-cli
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"   # Jaeger UI
      - "14268:14268"   # jaeger.thrift over HTTP
      - "6831:6831/udp" # jaeger.thrift over compact thrift protocol
      - "6832:6832/udp" # jaeger.thrift over binary thrift protocol
      - "4317:4317"     # OTLP gRPC receiver
      - "4318:4318"     # OTLP HTTP receiver
    networks:
      - jaeger-network

networks:
  jaeger-network:
    driver: bridge 