// flow-typed signature: 101ad345c63fa4b75a7ca13903cdd5dd
// flow-typed version: <<STUB>>/babel-preset-es2017_v^6.24.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2017'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2017' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-es2017/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-es2017/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-es2017/lib/index'>;
}
