// flow-typed signature: e87edc0534e0deae4ef223abc4f57150
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-block-scoping_v^6.26.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-block-scoping'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-block-scoping' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-es2015-block-scoping/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-es2015-block-scoping/lib/tdz' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-es2015-block-scoping/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-block-scoping/lib/index'>;
}
declare module 'babel-plugin-transform-es2015-block-scoping/lib/tdz.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-block-scoping/lib/tdz'>;
}
