// flow-typed signature: db8c7d40a8ec07600efafbe59db4197b
// flow-typed version: <<STUB>>/cli-spinner_v^0.2.6/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cli-spinner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cli-spinner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cli-spinner/example/spinner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cli-spinner/example/spinner.js' {
  declare module.exports: $Exports<'cli-spinner/example/spinner'>;
}
declare module 'cli-spinner/index' {
  declare module.exports: $Exports<'cli-spinner'>;
}
declare module 'cli-spinner/index.js' {
  declare module.exports: $Exports<'cli-spinner'>;
}
