// flow-typed signature: d3fd00b0e27beee612f86cc5638fa301
// flow-typed version: <<STUB>>/copyfiles_v^1.2.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copyfiles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'copyfiles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'copyfiles/test/test.fromNode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'copyfiles/index' {
  declare module.exports: $Exports<'copyfiles'>;
}
declare module 'copyfiles/index.js' {
  declare module.exports: $Exports<'copyfiles'>;
}
declare module 'copyfiles/test/test.fromNode.js' {
  declare module.exports: $Exports<'copyfiles/test/test.fromNode'>;
}
