// flow-typed signature: 8d47c428179c795674ad420a1c21adbb
// flow-typed version: <<STUB>>/img-diff-js_v^0.4.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'img-diff-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'img-diff-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'img-diff-js/lib/decode-jpeg' {
  declare module.exports: any;
}

declare module 'img-diff-js/lib/decode-png' {
  declare module.exports: any;
}

declare module 'img-diff-js/lib/decode-tiff' {
  declare module.exports: any;
}

declare module 'img-diff-js/lib/expand' {
  declare module.exports: any;
}

declare module 'img-diff-js/lib/index' {
  declare module.exports: any;
}

declare module 'img-diff-js/tool/perf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'img-diff-js/lib/decode-jpeg.js' {
  declare module.exports: $Exports<'img-diff-js/lib/decode-jpeg'>;
}
declare module 'img-diff-js/lib/decode-png.js' {
  declare module.exports: $Exports<'img-diff-js/lib/decode-png'>;
}
declare module 'img-diff-js/lib/decode-tiff.js' {
  declare module.exports: $Exports<'img-diff-js/lib/decode-tiff'>;
}
declare module 'img-diff-js/lib/expand.js' {
  declare module.exports: $Exports<'img-diff-js/lib/expand'>;
}
declare module 'img-diff-js/lib/index.js' {
  declare module.exports: $Exports<'img-diff-js/lib/index'>;
}
declare module 'img-diff-js/tool/perf.js' {
  declare module.exports: $Exports<'img-diff-js/tool/perf'>;
}
