// flow-typed signature: 598f7f6de3cca2bd0c0a1fb0adff6f9b
// flow-typed version: <<STUB>>/make-dir_v^1.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'make-dir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'make-dir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'make-dir/index' {
  declare module.exports: $Exports<'make-dir'>;
}
declare module 'make-dir/index.js' {
  declare module.exports: $Exports<'make-dir'>;
}
