// flow-typed signature: 27e77d5a06f741b9e737a754a65f33a9
// flow-typed version: <<STUB>>/mustache_v^2.3.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mustache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mustache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mustache/mustache' {
  declare module.exports: any;
}

declare module 'mustache/mustache.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mustache/mustache.js' {
  declare module.exports: $Exports<'mustache/mustache'>;
}
declare module 'mustache/mustache.min.js' {
  declare module.exports: $Exports<'mustache/mustache.min'>;
}
