// flow-typed signature: bba32553c057327629d930d8272be038
// flow-typed version: <<STUB>>/reg-publish-s3-plugin_v^0.6.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reg-publish-s3-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reg-publish-s3-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reg-publish-s3-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'reg-publish-s3-plugin/lib/s3-bucket-preparer' {
  declare module.exports: any;
}

declare module 'reg-publish-s3-plugin/lib/s3-publisher-plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reg-publish-s3-plugin/lib/index.js' {
  declare module.exports: $Exports<'reg-publish-s3-plugin/lib/index'>;
}
declare module 'reg-publish-s3-plugin/lib/s3-bucket-preparer.js' {
  declare module.exports: $Exports<'reg-publish-s3-plugin/lib/s3-bucket-preparer'>;
}
declare module 'reg-publish-s3-plugin/lib/s3-publisher-plugin.js' {
  declare module.exports: $Exports<'reg-publish-s3-plugin/lib/s3-publisher-plugin'>;
}
