// flow-typed signature: cdb84c8655962e11304b99f2ca8c7d47
// flow-typed version: <<STUB>>/reg-keygen-git-hash-plugin_v^0.5.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reg-keygen-git-hash-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reg-keygen-git-hash-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reg-keygen-git-hash-plugin/lib/commit-explorer' {
  declare module.exports: any;
}

declare module 'reg-keygen-git-hash-plugin/lib/git-cmd-client' {
  declare module.exports: any;
}

declare module 'reg-keygen-git-hash-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'reg-keygen-git-hash-plugin/lib/testing/git-log-loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reg-keygen-git-hash-plugin/lib/commit-explorer.js' {
  declare module.exports: $Exports<'reg-keygen-git-hash-plugin/lib/commit-explorer'>;
}
declare module 'reg-keygen-git-hash-plugin/lib/git-cmd-client.js' {
  declare module.exports: $Exports<'reg-keygen-git-hash-plugin/lib/git-cmd-client'>;
}
declare module 'reg-keygen-git-hash-plugin/lib/index.js' {
  declare module.exports: $Exports<'reg-keygen-git-hash-plugin/lib/index'>;
}
declare module 'reg-keygen-git-hash-plugin/lib/testing/git-log-loader.js' {
  declare module.exports: $Exports<'reg-keygen-git-hash-plugin/lib/testing/git-log-loader'>;
}
