// flow-typed signature: 2fb36989f7274d45e5d2dcb9d5221ba2
// flow-typed version: <<STUB>>/reg-notify-github-plugin_v^0.6.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reg-notify-github-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reg-notify-github-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reg-notify-github-plugin/lib/git-config-parser' {
  declare module.exports: any;
}

declare module 'reg-notify-github-plugin/lib/github-notifier-plugin' {
  declare module.exports: any;
}

declare module 'reg-notify-github-plugin/lib/github-preparer' {
  declare module.exports: any;
}

declare module 'reg-notify-github-plugin/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reg-notify-github-plugin/lib/git-config-parser.js' {
  declare module.exports: $Exports<'reg-notify-github-plugin/lib/git-config-parser'>;
}
declare module 'reg-notify-github-plugin/lib/github-notifier-plugin.js' {
  declare module.exports: $Exports<'reg-notify-github-plugin/lib/github-notifier-plugin'>;
}
declare module 'reg-notify-github-plugin/lib/github-preparer.js' {
  declare module.exports: $Exports<'reg-notify-github-plugin/lib/github-preparer'>;
}
declare module 'reg-notify-github-plugin/lib/index.js' {
  declare module.exports: $Exports<'reg-notify-github-plugin/lib/index'>;
}
