// flow-typed signature: ee6dbed18f85806ea073092a74e2868b
// flow-typed version: <<STUB>>/require-extension-hooks_v^0.3.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'require-extension-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'require-extension-hooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'require-extension-hooks/src/api' {
  declare module.exports: any;
}

declare module 'require-extension-hooks/src/cache' {
  declare module.exports: any;
}

declare module 'require-extension-hooks/src/hook' {
  declare module.exports: any;
}

declare module 'require-extension-hooks/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'require-extension-hooks/src/api.js' {
  declare module.exports: $Exports<'require-extension-hooks/src/api'>;
}
declare module 'require-extension-hooks/src/cache.js' {
  declare module.exports: $Exports<'require-extension-hooks/src/cache'>;
}
declare module 'require-extension-hooks/src/hook.js' {
  declare module.exports: $Exports<'require-extension-hooks/src/hook'>;
}
declare module 'require-extension-hooks/src/index.js' {
  declare module.exports: $Exports<'require-extension-hooks/src/index'>;
}
