// flow-typed signature: 859332cfe3fa54576526d45f808d44aa
// flow-typed version: <<STUB>>/require-extension-hooks-babel_v^0.1.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'require-extension-hooks-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'require-extension-hooks-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'require-extension-hooks-babel/index' {
  declare module.exports: $Exports<'require-extension-hooks-babel'>;
}
declare module 'require-extension-hooks-babel/index.js' {
  declare module.exports: $Exports<'require-extension-hooks-babel'>;
}
