// flow-typed signature: e63e648ad23b1a006027edee56bd0027
// flow-typed version: <<STUB>>/require-extension-hooks-vue_v^0.4.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'require-extension-hooks-vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'require-extension-hooks-vue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'require-extension-hooks-vue/src/index' {
  declare module.exports: any;
}

declare module 'require-extension-hooks-vue/src/renderTemplate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'require-extension-hooks-vue/src/index.js' {
  declare module.exports: $Exports<'require-extension-hooks-vue/src/index'>;
}
declare module 'require-extension-hooks-vue/src/renderTemplate.js' {
  declare module.exports: $Exports<'require-extension-hooks-vue/src/renderTemplate'>;
}
