// flow-typed signature: b9b6094a63218b5496776e97a49611a4
// flow-typed version: <<STUB>>/vue-thin-modal_v^0.2.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-thin-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-thin-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-thin-modal/dist/vue-thin-modal.cjs' {
  declare module.exports: any;
}

declare module 'vue-thin-modal/dist/vue-thin-modal' {
  declare module.exports: any;
}

declare module 'vue-thin-modal/dist/vue-thin-modal.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-thin-modal/dist/vue-thin-modal.cjs.js' {
  declare module.exports: $Exports<'vue-thin-modal/dist/vue-thin-modal.cjs'>;
}
declare module 'vue-thin-modal/dist/vue-thin-modal.js' {
  declare module.exports: $Exports<'vue-thin-modal/dist/vue-thin-modal'>;
}
declare module 'vue-thin-modal/dist/vue-thin-modal.min.js' {
  declare module.exports: $Exports<'vue-thin-modal/dist/vue-thin-modal.min'>;
}
