// flow-typed signature: 8f32dd23b7a079fa1e3e5ea796c84508
// flow-typed version: <<STUB>>/x-img-diff-js_v0.3.5/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'x-img-diff-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'x-img-diff-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'x-img-diff-js/binding-gen/post' {
  declare module.exports: any;
}

declare module 'x-img-diff-js/build/cv-wasm_browser' {
  declare module.exports: any;
}

declare module 'x-img-diff-js/build/cv-wasm_node' {
  declare module.exports: any;
}

declare module 'x-img-diff-js/src/index' {
  declare module.exports: any;
}

declare module 'x-img-diff-js/test/test_node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'x-img-diff-js/binding-gen/post.js' {
  declare module.exports: $Exports<'x-img-diff-js/binding-gen/post'>;
}
declare module 'x-img-diff-js/build/cv-wasm_browser.js' {
  declare module.exports: $Exports<'x-img-diff-js/build/cv-wasm_browser'>;
}
declare module 'x-img-diff-js/build/cv-wasm_node.js' {
  declare module.exports: $Exports<'x-img-diff-js/build/cv-wasm_node'>;
}
declare module 'x-img-diff-js/src/index.js' {
  declare module.exports: $Exports<'x-img-diff-js/src/index'>;
}
declare module 'x-img-diff-js/test/test_node.js' {
  declare module.exports: $Exports<'x-img-diff-js/test/test_node'>;
}
